"""editing cost table

Revision ID: 0001990d4b19
Revises: e21aae64252b
Create Date: 2019-05-07 10:03:36.207324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001990d4b19'
down_revision = 'e21aae64252b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apartment_per_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_weekly_cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('beer_at_establishment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('coffee_at_establishment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gas_one_liter', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hostel_per_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hotel_per_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('house_per_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('km_per_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('restaurant_inexpensive_meal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tent_per_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('van_per_day', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cost_apartment_per_day'), ['apartment_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_avg_weekly_cost'), ['avg_weekly_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_beer_at_establishment'), ['beer_at_establishment'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_coffee_at_establishment'), ['coffee_at_establishment'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_gas_one_liter'), ['gas_one_liter'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_hostel_per_day'), ['hostel_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_hotel_per_day'), ['hotel_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_house_per_day'), ['house_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_km_per_day'), ['km_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_restaurant_inexpensive_meal'), ['restaurant_inexpensive_meal'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_tent_per_day'), ['tent_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_van_per_day'), ['van_per_day'], unique=False)
        batch_op.drop_index('ix_cost_accomodation_most_common')
        batch_op.drop_index('ix_cost_airbnb_avg_per_night')
        batch_op.drop_index('ix_cost_apartment_long_term')
        batch_op.drop_index('ix_cost_beer_out')
        batch_op.drop_index('ix_cost_camping')
        batch_op.drop_index('ix_cost_cappucino_out')
        batch_op.drop_index('ix_cost_hostel')
        batch_op.drop_index('ix_cost_hotel')
        batch_op.drop_index('ix_cost_weekly_avg')
        batch_op.drop_index('ix_cost_wine_bottle_store')
        batch_op.drop_column('hotel')
        batch_op.drop_column('accomodation_most_common')
        batch_op.drop_column('beer_out')
        batch_op.drop_column('camping')
        batch_op.drop_column('airbnb_avg_per_night')
        batch_op.drop_column('apartment_long_term')
        batch_op.drop_column('wine_bottle_store')
        batch_op.drop_column('weekly_avg')
        batch_op.drop_column('currency')
        batch_op.drop_column('hostel')
        batch_op.drop_column('cappucino_out')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cappucino_out', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('hostel', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.NCHAR(length=3), nullable=True))
        batch_op.add_column(sa.Column('weekly_avg', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('wine_bottle_store', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('apartment_long_term', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('airbnb_avg_per_night', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('camping', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('beer_out', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('accomodation_most_common', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('hotel', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_cost_wine_bottle_store', ['wine_bottle_store'], unique=False)
        batch_op.create_index('ix_cost_weekly_avg', ['weekly_avg'], unique=False)
        batch_op.create_index('ix_cost_hotel', ['hotel'], unique=False)
        batch_op.create_index('ix_cost_hostel', ['hostel'], unique=False)
        batch_op.create_index('ix_cost_cappucino_out', ['cappucino_out'], unique=False)
        batch_op.create_index('ix_cost_camping', ['camping'], unique=False)
        batch_op.create_index('ix_cost_beer_out', ['beer_out'], unique=False)
        batch_op.create_index('ix_cost_apartment_long_term', ['apartment_long_term'], unique=False)
        batch_op.create_index('ix_cost_airbnb_avg_per_night', ['airbnb_avg_per_night'], unique=False)
        batch_op.create_index('ix_cost_accomodation_most_common', ['accomodation_most_common'], unique=False)
        batch_op.drop_index(batch_op.f('ix_cost_van_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_tent_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_restaurant_inexpensive_meal'))
        batch_op.drop_index(batch_op.f('ix_cost_km_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_house_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_hotel_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_hostel_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_gas_one_liter'))
        batch_op.drop_index(batch_op.f('ix_cost_coffee_at_establishment'))
        batch_op.drop_index(batch_op.f('ix_cost_beer_at_establishment'))
        batch_op.drop_index(batch_op.f('ix_cost_avg_weekly_cost'))
        batch_op.drop_index(batch_op.f('ix_cost_apartment_per_day'))
        batch_op.drop_column('van_per_day')
        batch_op.drop_column('tent_per_day')
        batch_op.drop_column('restaurant_inexpensive_meal')
        batch_op.drop_column('km_per_day')
        batch_op.drop_column('house_per_day')
        batch_op.drop_column('hotel_per_day')
        batch_op.drop_column('hostel_per_day')
        batch_op.drop_column('gas_one_liter')
        batch_op.drop_column('coffee_at_establishment')
        batch_op.drop_column('beer_at_establishment')
        batch_op.drop_column('avg_weekly_cost')
        batch_op.drop_column('apartment_per_day')

    # ### end Alembic commands ###
