"""Adding column 'description' to destination table

Revision ID: 03661f8a7ab1
Revises: e4a4d58bd6c6
Create Date: 2019-05-14 10:39:53.247071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03661f8a7ab1'
down_revision = 'e4a4d58bd6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
