"""adding column 'description' type Text to destination table

Revision ID: 0c0eb5a167d3
Revises: 83f9d34915d6
Create Date: 2019-05-14 10:44:15.776944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0eb5a167d3'
down_revision = '83f9d34915d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
