"""empty message

Revision ID: 13cb99a5e7c7
Revises: 
Create Date: 2019-05-20 14:58:14.917119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cb99a5e7c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('displayname', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=280), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_displayname'), ['displayname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('weather_ltd', sa.Integer(), nullable=True),
    sa.Column('weather_lng', sa.Integer(), nullable=True),
    sa.Column('featured_photo_filename', sa.String(length=64), nullable=True),
    sa.Column('featured_photo_url', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_destination_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_destination_title'), ['title'], unique=True)

    op.create_table('accomodation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tent', sa.Boolean(), nullable=True),
    sa.Column('van', sa.Boolean(), nullable=True),
    sa.Column('hostel', sa.Boolean(), nullable=True),
    sa.Column('camping', sa.Boolean(), nullable=True),
    sa.Column('apartment', sa.Boolean(), nullable=True),
    sa.Column('house', sa.Boolean(), nullable=True),
    sa.Column('hotel', sa.Boolean(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accomodation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accomodation_apartment'), ['apartment'], unique=False)
        batch_op.create_index(batch_op.f('ix_accomodation_camping'), ['camping'], unique=False)
        batch_op.create_index(batch_op.f('ix_accomodation_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accomodation_hostel'), ['hostel'], unique=False)
        batch_op.create_index(batch_op.f('ix_accomodation_hotel'), ['hotel'], unique=False)
        batch_op.create_index(batch_op.f('ix_accomodation_house'), ['house'], unique=False)
        batch_op.create_index(batch_op.f('ix_accomodation_tent'), ['tent'], unique=False)
        batch_op.create_index(batch_op.f('ix_accomodation_van'), ['van'], unique=False)

    op.create_table('additional_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('additional_photo_filename', sa.String(length=64), nullable=True),
    sa.Column('additional_photo_url', sa.String(length=256), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('additional_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_additional_photos_destination_id'), ['destination_id'], unique=False)

    op.create_table('approach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('easy', sa.Boolean(), nullable=True),
    sa.Column('moderate', sa.Boolean(), nullable=True),
    sa.Column('hardcore', sa.Boolean(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approach', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approach_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approach_easy'), ['easy'], unique=False)
        batch_op.create_index(batch_op.f('ix_approach_hardcore'), ['hardcore'], unique=False)
        batch_op.create_index(batch_op.f('ix_approach_moderate'), ['moderate'], unique=False)

    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('not_needed', sa.Boolean(), nullable=True),
    sa.Column('good_to_have', sa.Boolean(), nullable=True),
    sa.Column('must_have', sa.Boolean(), nullable=True),
    sa.Column('rent_scooter_locally', sa.Boolean(), nullable=True),
    sa.Column('rent_car_locally', sa.Boolean(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_good_to_have'), ['good_to_have'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_must_have'), ['must_have'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_not_needed'), ['not_needed'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_rent_car_locally'), ['rent_car_locally'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_rent_scooter_locally'), ['rent_scooter_locally'], unique=False)

    op.create_table('cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_form_currency', sa.String(length=32), nullable=True),
    sa.Column('beer_at_establishment', sa.Float(), nullable=True),
    sa.Column('coffee_at_establishment', sa.Float(), nullable=True),
    sa.Column('restaurant_inexpensive_meal', sa.Float(), nullable=True),
    sa.Column('groceries_one_week', sa.Float(), nullable=True),
    sa.Column('car_rent_one_week', sa.Float(), nullable=True),
    sa.Column('gas_one_liter', sa.Float(), nullable=True),
    sa.Column('km_per_day', sa.Float(), nullable=True),
    sa.Column('tent_per_day', sa.Float(), nullable=True),
    sa.Column('van_per_day', sa.Float(), nullable=True),
    sa.Column('camping_per_day', sa.Float(), nullable=True),
    sa.Column('hostel_per_day', sa.Float(), nullable=True),
    sa.Column('apartment_per_day', sa.Float(), nullable=True),
    sa.Column('house_per_day', sa.Float(), nullable=True),
    sa.Column('hotel_per_day', sa.Float(), nullable=True),
    sa.Column('accomodation_used_for_avg_weekly_cost', sa.String(), nullable=True),
    sa.Column('avg_weekly_cost', sa.Float(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_accomodation_used_for_avg_weekly_cost'), ['accomodation_used_for_avg_weekly_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_apartment_per_day'), ['apartment_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_avg_weekly_cost'), ['avg_weekly_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_beer_at_establishment'), ['beer_at_establishment'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_camping_per_day'), ['camping_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_car_rent_one_week'), ['car_rent_one_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_coffee_at_establishment'), ['coffee_at_establishment'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_gas_one_liter'), ['gas_one_liter'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_groceries_one_week'), ['groceries_one_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_hostel_per_day'), ['hostel_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_hotel_per_day'), ['hotel_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_house_per_day'), ['house_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_km_per_day'), ['km_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_restaurant_inexpensive_meal'), ['restaurant_inexpensive_meal'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_tent_per_day'), ['tent_per_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_van_per_day'), ['van_per_day'], unique=False)

    op.create_table('months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('january', sa.Boolean(), nullable=True),
    sa.Column('february', sa.Boolean(), nullable=True),
    sa.Column('mars', sa.Boolean(), nullable=True),
    sa.Column('april', sa.Boolean(), nullable=True),
    sa.Column('may', sa.Boolean(), nullable=True),
    sa.Column('june', sa.Boolean(), nullable=True),
    sa.Column('july', sa.Boolean(), nullable=True),
    sa.Column('august', sa.Boolean(), nullable=True),
    sa.Column('september', sa.Boolean(), nullable=True),
    sa.Column('october', sa.Boolean(), nullable=True),
    sa.Column('november', sa.Boolean(), nullable=True),
    sa.Column('december', sa.Boolean(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('months', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_months_april'), ['april'], unique=False)
        batch_op.create_index(batch_op.f('ix_months_august'), ['august'], unique=False)
        batch_op.create_index(batch_op.f('ix_months_december'), ['december'], unique=False)
        batch_op.create_index(batch_op.f('ix_months_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_months_february'), ['february'], unique=False)
        batch_op.create_index(batch_op.f('ix_months_january'), ['january'], unique=False)
        batch_op.create_index(batch_op.f('ix_months_july'), ['july'], unique=False)
        batch_op.create_index(batch_op.f('ix_months_june'), ['june'], unique=False)
        batch_op.create_index(batch_op.f('ix_months_mars'), ['mars'], unique=False)
        batch_op.create_index(batch_op.f('ix_months_may'), ['may'], unique=False)
        batch_op.create_index(batch_op.f('ix_months_november'), ['november'], unique=False)
        batch_op.create_index(batch_op.f('ix_months_october'), ['october'], unique=False)
        batch_op.create_index(batch_op.f('ix_months_september'), ['september'], unique=False)

    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traditional', sa.Boolean(), nullable=True),
    sa.Column('sport', sa.Boolean(), nullable=True),
    sa.Column('bouldering', sa.Boolean(), nullable=True),
    sa.Column('main_discipline', sa.String(length=64), nullable=True),
    sa.Column('easy_routes', sa.Float(), nullable=True),
    sa.Column('intermediate_routes', sa.Float(), nullable=True),
    sa.Column('hard_routes', sa.Float(), nullable=True),
    sa.Column('very_hard_routes', sa.Float(), nullable=True),
    sa.Column('total_routes', sa.Integer(), nullable=True),
    sa.Column('total_trad', sa.Integer(), nullable=True),
    sa.Column('total_sport', sa.Integer(), nullable=True),
    sa.Column('total_boulders', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_bouldering'), ['bouldering'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_easy_routes'), ['easy_routes'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_hard_routes'), ['hard_routes'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_intermediate_routes'), ['intermediate_routes'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_main_discipline'), ['main_discipline'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_sport'), ['sport'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_total_boulders'), ['total_boulders'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_total_routes'), ['total_routes'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_total_sport'), ['total_sport'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_total_trad'), ['total_trad'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_traditional'), ['traditional'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_very_hard_routes'), ['very_hard_routes'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_very_hard_routes'))
        batch_op.drop_index(batch_op.f('ix_routes_traditional'))
        batch_op.drop_index(batch_op.f('ix_routes_total_trad'))
        batch_op.drop_index(batch_op.f('ix_routes_total_sport'))
        batch_op.drop_index(batch_op.f('ix_routes_total_routes'))
        batch_op.drop_index(batch_op.f('ix_routes_total_boulders'))
        batch_op.drop_index(batch_op.f('ix_routes_sport'))
        batch_op.drop_index(batch_op.f('ix_routes_main_discipline'))
        batch_op.drop_index(batch_op.f('ix_routes_intermediate_routes'))
        batch_op.drop_index(batch_op.f('ix_routes_hard_routes'))
        batch_op.drop_index(batch_op.f('ix_routes_easy_routes'))
        batch_op.drop_index(batch_op.f('ix_routes_destination_id'))
        batch_op.drop_index(batch_op.f('ix_routes_bouldering'))

    op.drop_table('routes')
    with op.batch_alter_table('months', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_months_september'))
        batch_op.drop_index(batch_op.f('ix_months_october'))
        batch_op.drop_index(batch_op.f('ix_months_november'))
        batch_op.drop_index(batch_op.f('ix_months_may'))
        batch_op.drop_index(batch_op.f('ix_months_mars'))
        batch_op.drop_index(batch_op.f('ix_months_june'))
        batch_op.drop_index(batch_op.f('ix_months_july'))
        batch_op.drop_index(batch_op.f('ix_months_january'))
        batch_op.drop_index(batch_op.f('ix_months_february'))
        batch_op.drop_index(batch_op.f('ix_months_destination_id'))
        batch_op.drop_index(batch_op.f('ix_months_december'))
        batch_op.drop_index(batch_op.f('ix_months_august'))
        batch_op.drop_index(batch_op.f('ix_months_april'))

    op.drop_table('months')
    with op.batch_alter_table('cost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_van_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_tent_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_restaurant_inexpensive_meal'))
        batch_op.drop_index(batch_op.f('ix_cost_km_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_house_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_hotel_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_hostel_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_groceries_one_week'))
        batch_op.drop_index(batch_op.f('ix_cost_gas_one_liter'))
        batch_op.drop_index(batch_op.f('ix_cost_destination_id'))
        batch_op.drop_index(batch_op.f('ix_cost_coffee_at_establishment'))
        batch_op.drop_index(batch_op.f('ix_cost_car_rent_one_week'))
        batch_op.drop_index(batch_op.f('ix_cost_camping_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_beer_at_establishment'))
        batch_op.drop_index(batch_op.f('ix_cost_avg_weekly_cost'))
        batch_op.drop_index(batch_op.f('ix_cost_apartment_per_day'))
        batch_op.drop_index(batch_op.f('ix_cost_accomodation_used_for_avg_weekly_cost'))

    op.drop_table('cost')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_rent_scooter_locally'))
        batch_op.drop_index(batch_op.f('ix_car_rent_car_locally'))
        batch_op.drop_index(batch_op.f('ix_car_not_needed'))
        batch_op.drop_index(batch_op.f('ix_car_must_have'))
        batch_op.drop_index(batch_op.f('ix_car_good_to_have'))
        batch_op.drop_index(batch_op.f('ix_car_destination_id'))

    op.drop_table('car')
    with op.batch_alter_table('approach', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approach_moderate'))
        batch_op.drop_index(batch_op.f('ix_approach_hardcore'))
        batch_op.drop_index(batch_op.f('ix_approach_easy'))
        batch_op.drop_index(batch_op.f('ix_approach_destination_id'))

    op.drop_table('approach')
    with op.batch_alter_table('additional_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_additional_photos_destination_id'))

    op.drop_table('additional_photos')
    with op.batch_alter_table('accomodation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accomodation_van'))
        batch_op.drop_index(batch_op.f('ix_accomodation_tent'))
        batch_op.drop_index(batch_op.f('ix_accomodation_house'))
        batch_op.drop_index(batch_op.f('ix_accomodation_hotel'))
        batch_op.drop_index(batch_op.f('ix_accomodation_hostel'))
        batch_op.drop_index(batch_op.f('ix_accomodation_destination_id'))
        batch_op.drop_index(batch_op.f('ix_accomodation_camping'))
        batch_op.drop_index(batch_op.f('ix_accomodation_apartment'))

    op.drop_table('accomodation')
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destination_title'))
        batch_op.drop_index(batch_op.f('ix_destination_country'))

    op.drop_table('destination')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_location'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_displayname'))

    op.drop_table('user')
    # ### end Alembic commands ###
