"""Fix: march instead of mars in months table

Revision ID: 195e9496df70
Revises: ecb5074283ea
Create Date: 2019-09-29 15:48:51.206848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195e9496df70'
down_revision = 'ecb5074283ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('months', schema=None) as batch_op:
        batch_op.add_column(sa.Column('march', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_months_march'), ['march'], unique=False)
        batch_op.drop_index('ix_months_mars')
        batch_op.drop_column('mars')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('months', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mars', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('ix_months_mars', ['mars'], unique=False)
        batch_op.drop_index(batch_op.f('ix_months_march'))
        batch_op.drop_column('march')

    # ### end Alembic commands ###
