"""adding access roles

Revision ID: 3b3b1e9880ab
Revises: c7a95c76e625
Create Date: 2019-05-23 11:48:23.080834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3b1e9880ab'
down_revision = 'c7a95c76e625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_access'), ['access'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_access'))
        batch_op.drop_column('access')

    # ### end Alembic commands ###
