"""adding stuff to cost table

Revision ID: 5e85a1dec6e3
Revises: c6f7befdd918
Create Date: 2019-01-23 12:40:57.470403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e85a1dec6e3'
down_revision = 'c6f7befdd918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost', sa.Column('accomodation_most_common', sa.Integer(), nullable=True))
    op.add_column('cost', sa.Column('airbnb_avg_per_night', sa.Integer(), nullable=True))
    op.add_column('cost', sa.Column('beer_out', sa.Integer(), nullable=True))
    op.add_column('cost', sa.Column('camping', sa.Integer(), nullable=True))
    op.add_column('cost', sa.Column('cappucino_out', sa.Integer(), nullable=True))
    op.add_column('cost', sa.Column('car_rent_one_week', sa.Integer(), nullable=True))
    op.add_column('cost', sa.Column('groceries_one_week', sa.Integer(), nullable=True))
    op.add_column('cost', sa.Column('van_free', sa.Boolean(), nullable=True))
    op.add_column('cost', sa.Column('wine_bottle_store', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cost_accomodation_most_common'), 'cost', ['accomodation_most_common'], unique=False)
    op.create_index(op.f('ix_cost_airbnb_avg_per_night'), 'cost', ['airbnb_avg_per_night'], unique=False)
    op.create_index(op.f('ix_cost_beer_out'), 'cost', ['beer_out'], unique=False)
    op.create_index(op.f('ix_cost_camping'), 'cost', ['camping'], unique=False)
    op.create_index(op.f('ix_cost_cappucino_out'), 'cost', ['cappucino_out'], unique=False)
    op.create_index(op.f('ix_cost_car_rent_one_week'), 'cost', ['car_rent_one_week'], unique=False)
    op.create_index(op.f('ix_cost_groceries_one_week'), 'cost', ['groceries_one_week'], unique=False)
    op.create_index(op.f('ix_cost_van_free'), 'cost', ['van_free'], unique=False)
    op.create_index(op.f('ix_cost_wine_bottle_store'), 'cost', ['wine_bottle_store'], unique=False)

    op.alter_column('cost', 'tent', new_column_name='tent_free')
    op.alter_column('cost', 'apartment', new_column_name='apartment_long_term')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost', sa.Column('tent', sa.INTEGER(), nullable=True))
    op.add_column('cost', sa.Column('apartment', sa.INTEGER(), nullable=True))
    op.create_index('ix_cost_tent', 'cost', ['tent'], unique=False)
    op.create_index('ix_cost_apartment', 'cost', ['apartment'], unique=False)
    op.drop_index(op.f('ix_cost_wine_bottle_store'), table_name='cost')
    op.drop_index(op.f('ix_cost_van_free'), table_name='cost')
    op.drop_index(op.f('ix_cost_tent_free'), table_name='cost')
    op.drop_index(op.f('ix_cost_groceries_one_week'), table_name='cost')
    op.drop_index(op.f('ix_cost_car_rent_one_week'), table_name='cost')
    op.drop_index(op.f('ix_cost_cappucino_out'), table_name='cost')
    op.drop_index(op.f('ix_cost_camping'), table_name='cost')
    op.drop_index(op.f('ix_cost_beer_out'), table_name='cost')
    op.drop_index(op.f('ix_cost_apartment_long_term'), table_name='cost')
    op.drop_index(op.f('ix_cost_airbnb_avg_per_night'), table_name='cost')
    op.drop_index(op.f('ix_cost_accomodation_most_common'), table_name='cost')
    op.drop_column('cost', 'wine_bottle_store')
    op.drop_column('cost', 'van_free')
    op.drop_column('cost', 'tent_free')
    op.drop_column('cost', 'groceries_one_week')
    op.drop_column('cost', 'car_rent_one_week')
    op.drop_column('cost', 'cappucino_out')
    op.drop_column('cost', 'camping')
    op.drop_column('cost', 'beer_out')
    op.drop_column('cost', 'apartment_long_term')
    op.drop_column('cost', 'airbnb_avg_per_night')
    op.drop_column('cost', 'accomodation_most_common')
    # ### end Alembic commands ###
