"""changing tent and van col names

Revision ID: 81a2ee3df2e0
Revises: aa377432a9ea
Create Date: 2019-01-23 14:24:33.914292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a2ee3df2e0'
down_revision = 'aa377432a9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accomodation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tent_free', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('van_free', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_accomodation_tent_free'), ['tent_free'], unique=False)
        batch_op.create_index(batch_op.f('ix_accomodation_van_free'), ['van_free'], unique=False)
        batch_op.drop_index('ix_accomodation_tent')
        batch_op.drop_index('ix_accomodation_van')
        batch_op.drop_column('tent')
        batch_op.drop_column('van')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accomodation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('van', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('tent', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('ix_accomodation_van', ['van'], unique=False)
        batch_op.create_index('ix_accomodation_tent', ['tent'], unique=False)
        batch_op.drop_index(batch_op.f('ix_accomodation_van_free'))
        batch_op.drop_index(batch_op.f('ix_accomodation_tent_free'))
        batch_op.drop_column('van_free')
        batch_op.drop_column('tent_free')

    # ### end Alembic commands ###
