"""fixing accomodation table

Revision ID: 849fb7127501
Revises: b54d4f943ed0
Create Date: 2019-05-07 14:45:07.881130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849fb7127501'
down_revision = 'b54d4f943ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accomodation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('van', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_accomodation_tent'), ['tent'], unique=False)
        batch_op.create_index(batch_op.f('ix_accomodation_van'), ['van'], unique=False)
        batch_op.drop_index('ix_accomodation_tent_free')
        batch_op.drop_index('ix_accomodation_van_free')
        batch_op.drop_column('van_free')
        batch_op.drop_column('tent_free')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accomodation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tent_free', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('van_free', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('ix_accomodation_van_free', ['van_free'], unique=False)
        batch_op.create_index('ix_accomodation_tent_free', ['tent_free'], unique=False)
        batch_op.drop_index(batch_op.f('ix_accomodation_van'))
        batch_op.drop_index(batch_op.f('ix_accomodation_tent'))
        batch_op.drop_column('van')
        batch_op.drop_column('tent')

    # ### end Alembic commands ###
