"""Fixing accomodation database table

Revision ID: aa377432a9ea
Revises: 5e85a1dec6e3
Create Date: 2019-01-23 13:58:44.982168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa377432a9ea'
down_revision = '5e85a1dec6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_apartment_long_term'), ['apartment_long_term'], unique=False)
        batch_op.drop_index('ix_cost_apartment')
        batch_op.drop_index('ix_cost_tent')
        batch_op.drop_index('ix_cost_van_free')
        batch_op.drop_column('van_free')
        batch_op.drop_column('tent_free')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tent_free', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('van_free', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('ix_cost_van_free', ['van_free'], unique=False)
        batch_op.create_index('ix_cost_tent', ['tent_free'], unique=False)
        batch_op.create_index('ix_cost_apartment', ['apartment_long_term'], unique=False)
        batch_op.drop_index(batch_op.f('ix_cost_apartment_long_term'))

    # ### end Alembic commands ###
