"""Added better structure for discipline types.

Revision ID: c6f7befdd918
Revises: 
Create Date: 2018-11-10 09:43:05.505197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f7befdd918'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('image_filename', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destination_country'), 'destination', ['country'], unique=False)
    op.create_index(op.f('ix_destination_title'), 'destination', ['title'], unique=True)
    op.create_table('accomodation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tent', sa.Boolean(), nullable=True),
    sa.Column('van', sa.Boolean(), nullable=True),
    sa.Column('hostel', sa.Boolean(), nullable=True),
    sa.Column('camping', sa.Boolean(), nullable=True),
    sa.Column('apartment', sa.Boolean(), nullable=True),
    sa.Column('house', sa.Boolean(), nullable=True),
    sa.Column('hotel', sa.Boolean(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accomodation_apartment'), 'accomodation', ['apartment'], unique=False)
    op.create_index(op.f('ix_accomodation_camping'), 'accomodation', ['camping'], unique=False)
    op.create_index(op.f('ix_accomodation_destination_id'), 'accomodation', ['destination_id'], unique=False)
    op.create_index(op.f('ix_accomodation_hostel'), 'accomodation', ['hostel'], unique=False)
    op.create_index(op.f('ix_accomodation_hotel'), 'accomodation', ['hotel'], unique=False)
    op.create_index(op.f('ix_accomodation_house'), 'accomodation', ['house'], unique=False)
    op.create_index(op.f('ix_accomodation_tent'), 'accomodation', ['tent'], unique=False)
    op.create_index(op.f('ix_accomodation_van'), 'accomodation', ['van'], unique=False)
    op.create_table('approach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('easy', sa.Boolean(), nullable=True),
    sa.Column('moderate', sa.Boolean(), nullable=True),
    sa.Column('hardcore', sa.Boolean(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approach_destination_id'), 'approach', ['destination_id'], unique=False)
    op.create_index(op.f('ix_approach_easy'), 'approach', ['easy'], unique=False)
    op.create_index(op.f('ix_approach_hardcore'), 'approach', ['hardcore'], unique=False)
    op.create_index(op.f('ix_approach_moderate'), 'approach', ['moderate'], unique=False)
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('not_needed', sa.Boolean(), nullable=True),
    sa.Column('good_to_have', sa.Boolean(), nullable=True),
    sa.Column('must_have', sa.Boolean(), nullable=True),
    sa.Column('rent_scooter_locally', sa.Boolean(), nullable=True),
    sa.Column('rent_car_locally', sa.Boolean(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_destination_id'), 'car', ['destination_id'], unique=False)
    op.create_index(op.f('ix_car_good_to_have'), 'car', ['good_to_have'], unique=False)
    op.create_index(op.f('ix_car_must_have'), 'car', ['must_have'], unique=False)
    op.create_index(op.f('ix_car_not_needed'), 'car', ['not_needed'], unique=False)
    op.create_index(op.f('ix_car_rent_car_locally'), 'car', ['rent_car_locally'], unique=False)
    op.create_index(op.f('ix_car_rent_scooter_locally'), 'car', ['rent_scooter_locally'], unique=False)
    op.create_table('cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_avg', sa.Integer(), nullable=True),
    sa.Column('tent', sa.Integer(), nullable=True),
    sa.Column('hostel', sa.Integer(), nullable=True),
    sa.Column('apartment', sa.Integer(), nullable=True),
    sa.Column('hotel', sa.Integer(), nullable=True),
    sa.Column('currency', sa.NCHAR(length=3), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_apartment'), 'cost', ['apartment'], unique=False)
    op.create_index(op.f('ix_cost_destination_id'), 'cost', ['destination_id'], unique=False)
    op.create_index(op.f('ix_cost_hostel'), 'cost', ['hostel'], unique=False)
    op.create_index(op.f('ix_cost_hotel'), 'cost', ['hotel'], unique=False)
    op.create_index(op.f('ix_cost_tent'), 'cost', ['tent'], unique=False)
    op.create_index(op.f('ix_cost_weekly_avg'), 'cost', ['weekly_avg'], unique=False)
    op.create_table('months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('january', sa.Boolean(), nullable=True),
    sa.Column('february', sa.Boolean(), nullable=True),
    sa.Column('mars', sa.Boolean(), nullable=True),
    sa.Column('april', sa.Boolean(), nullable=True),
    sa.Column('may', sa.Boolean(), nullable=True),
    sa.Column('june', sa.Boolean(), nullable=True),
    sa.Column('july', sa.Boolean(), nullable=True),
    sa.Column('august', sa.Boolean(), nullable=True),
    sa.Column('september', sa.Boolean(), nullable=True),
    sa.Column('october', sa.Boolean(), nullable=True),
    sa.Column('november', sa.Boolean(), nullable=True),
    sa.Column('december', sa.Boolean(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_months_april'), 'months', ['april'], unique=False)
    op.create_index(op.f('ix_months_august'), 'months', ['august'], unique=False)
    op.create_index(op.f('ix_months_december'), 'months', ['december'], unique=False)
    op.create_index(op.f('ix_months_destination_id'), 'months', ['destination_id'], unique=False)
    op.create_index(op.f('ix_months_february'), 'months', ['february'], unique=False)
    op.create_index(op.f('ix_months_january'), 'months', ['january'], unique=False)
    op.create_index(op.f('ix_months_july'), 'months', ['july'], unique=False)
    op.create_index(op.f('ix_months_june'), 'months', ['june'], unique=False)
    op.create_index(op.f('ix_months_mars'), 'months', ['mars'], unique=False)
    op.create_index(op.f('ix_months_may'), 'months', ['may'], unique=False)
    op.create_index(op.f('ix_months_november'), 'months', ['november'], unique=False)
    op.create_index(op.f('ix_months_october'), 'months', ['october'], unique=False)
    op.create_index(op.f('ix_months_september'), 'months', ['september'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traditional', sa.Boolean(), nullable=True),
    sa.Column('sport', sa.Boolean(), nullable=True),
    sa.Column('bouldering', sa.Boolean(), nullable=True),
    sa.Column('main_discipline', sa.String(length=64), nullable=True),
    sa.Column('2', sa.Integer(), nullable=True),
    sa.Column('3', sa.Integer(), nullable=True),
    sa.Column('Range_23', sa.Integer(), nullable=True),
    sa.Column('4', sa.Integer(), nullable=True),
    sa.Column('4+', sa.Integer(), nullable=True),
    sa.Column('Range_4', sa.Integer(), nullable=True),
    sa.Column('5a', sa.Integer(), nullable=True),
    sa.Column('5b', sa.Integer(), nullable=True),
    sa.Column('5c', sa.Integer(), nullable=True),
    sa.Column('Range_5', sa.Integer(), nullable=True),
    sa.Column('6a', sa.Integer(), nullable=True),
    sa.Column('6a+', sa.Integer(), nullable=True),
    sa.Column('6b', sa.Integer(), nullable=True),
    sa.Column('6b+', sa.Integer(), nullable=True),
    sa.Column('6c', sa.Integer(), nullable=True),
    sa.Column('6c+', sa.Integer(), nullable=True),
    sa.Column('Range_6', sa.Integer(), nullable=True),
    sa.Column('7a', sa.Integer(), nullable=True),
    sa.Column('7a+', sa.Integer(), nullable=True),
    sa.Column('7b', sa.Integer(), nullable=True),
    sa.Column('7b+', sa.Integer(), nullable=True),
    sa.Column('7c', sa.Integer(), nullable=True),
    sa.Column('7c+', sa.Integer(), nullable=True),
    sa.Column('Range_7', sa.Integer(), nullable=True),
    sa.Column('8a', sa.Integer(), nullable=True),
    sa.Column('8a+', sa.Integer(), nullable=True),
    sa.Column('8b', sa.Integer(), nullable=True),
    sa.Column('8b+', sa.Integer(), nullable=True),
    sa.Column('8c', sa.Integer(), nullable=True),
    sa.Column('8c+', sa.Integer(), nullable=True),
    sa.Column('Range_8', sa.Integer(), nullable=True),
    sa.Column('9a', sa.Integer(), nullable=True),
    sa.Column('9a+', sa.Integer(), nullable=True),
    sa.Column('9b', sa.Integer(), nullable=True),
    sa.Column('9b+', sa.Integer(), nullable=True),
    sa.Column('9c', sa.Integer(), nullable=True),
    sa.Column('Range_9', sa.Integer(), nullable=True),
    sa.Column('total_routes', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_2'), 'routes', ['2'], unique=False)
    op.create_index(op.f('ix_routes_3'), 'routes', ['3'], unique=False)
    op.create_index(op.f('ix_routes_4'), 'routes', ['4'], unique=False)
    op.create_index(op.f('ix_routes_4+'), 'routes', ['4+'], unique=False)
    op.create_index(op.f('ix_routes_5a'), 'routes', ['5a'], unique=False)
    op.create_index(op.f('ix_routes_5b'), 'routes', ['5b'], unique=False)
    op.create_index(op.f('ix_routes_5c'), 'routes', ['5c'], unique=False)
    op.create_index(op.f('ix_routes_6a'), 'routes', ['6a'], unique=False)
    op.create_index(op.f('ix_routes_6a+'), 'routes', ['6a+'], unique=False)
    op.create_index(op.f('ix_routes_6b'), 'routes', ['6b'], unique=False)
    op.create_index(op.f('ix_routes_6b+'), 'routes', ['6b+'], unique=False)
    op.create_index(op.f('ix_routes_6c'), 'routes', ['6c'], unique=False)
    op.create_index(op.f('ix_routes_6c+'), 'routes', ['6c+'], unique=False)
    op.create_index(op.f('ix_routes_7a'), 'routes', ['7a'], unique=False)
    op.create_index(op.f('ix_routes_7a+'), 'routes', ['7a+'], unique=False)
    op.create_index(op.f('ix_routes_7b'), 'routes', ['7b'], unique=False)
    op.create_index(op.f('ix_routes_7b+'), 'routes', ['7b+'], unique=False)
    op.create_index(op.f('ix_routes_7c'), 'routes', ['7c'], unique=False)
    op.create_index(op.f('ix_routes_7c+'), 'routes', ['7c+'], unique=False)
    op.create_index(op.f('ix_routes_8a'), 'routes', ['8a'], unique=False)
    op.create_index(op.f('ix_routes_8a+'), 'routes', ['8a+'], unique=False)
    op.create_index(op.f('ix_routes_8b'), 'routes', ['8b'], unique=False)
    op.create_index(op.f('ix_routes_8b+'), 'routes', ['8b+'], unique=False)
    op.create_index(op.f('ix_routes_8c'), 'routes', ['8c'], unique=False)
    op.create_index(op.f('ix_routes_8c+'), 'routes', ['8c+'], unique=False)
    op.create_index(op.f('ix_routes_9a'), 'routes', ['9a'], unique=False)
    op.create_index(op.f('ix_routes_9a+'), 'routes', ['9a+'], unique=False)
    op.create_index(op.f('ix_routes_9b'), 'routes', ['9b'], unique=False)
    op.create_index(op.f('ix_routes_9b+'), 'routes', ['9b+'], unique=False)
    op.create_index(op.f('ix_routes_9c'), 'routes', ['9c'], unique=False)
    op.create_index(op.f('ix_routes_Range_23'), 'routes', ['Range_23'], unique=False)
    op.create_index(op.f('ix_routes_Range_4'), 'routes', ['Range_4'], unique=False)
    op.create_index(op.f('ix_routes_Range_5'), 'routes', ['Range_5'], unique=False)
    op.create_index(op.f('ix_routes_Range_6'), 'routes', ['Range_6'], unique=False)
    op.create_index(op.f('ix_routes_Range_7'), 'routes', ['Range_7'], unique=False)
    op.create_index(op.f('ix_routes_Range_8'), 'routes', ['Range_8'], unique=False)
    op.create_index(op.f('ix_routes_Range_9'), 'routes', ['Range_9'], unique=False)
    op.create_index(op.f('ix_routes_bouldering'), 'routes', ['bouldering'], unique=False)
    op.create_index(op.f('ix_routes_destination_id'), 'routes', ['destination_id'], unique=False)
    op.create_index(op.f('ix_routes_main_discipline'), 'routes', ['main_discipline'], unique=False)
    op.create_index(op.f('ix_routes_sport'), 'routes', ['sport'], unique=False)
    op.create_index(op.f('ix_routes_total_routes'), 'routes', ['total_routes'], unique=False)
    op.create_index(op.f('ix_routes_traditional'), 'routes', ['traditional'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_traditional'), table_name='routes')
    op.drop_index(op.f('ix_routes_total_routes'), table_name='routes')
    op.drop_index(op.f('ix_routes_sport'), table_name='routes')
    op.drop_index(op.f('ix_routes_main_discipline'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_bouldering'), table_name='routes')
    op.drop_index(op.f('ix_routes_Range_9'), table_name='routes')
    op.drop_index(op.f('ix_routes_Range_8'), table_name='routes')
    op.drop_index(op.f('ix_routes_Range_7'), table_name='routes')
    op.drop_index(op.f('ix_routes_Range_6'), table_name='routes')
    op.drop_index(op.f('ix_routes_Range_5'), table_name='routes')
    op.drop_index(op.f('ix_routes_Range_4'), table_name='routes')
    op.drop_index(op.f('ix_routes_Range_23'), table_name='routes')
    op.drop_index(op.f('ix_routes_9c'), table_name='routes')
    op.drop_index(op.f('ix_routes_9b+'), table_name='routes')
    op.drop_index(op.f('ix_routes_9b'), table_name='routes')
    op.drop_index(op.f('ix_routes_9a+'), table_name='routes')
    op.drop_index(op.f('ix_routes_9a'), table_name='routes')
    op.drop_index(op.f('ix_routes_8c+'), table_name='routes')
    op.drop_index(op.f('ix_routes_8c'), table_name='routes')
    op.drop_index(op.f('ix_routes_8b+'), table_name='routes')
    op.drop_index(op.f('ix_routes_8b'), table_name='routes')
    op.drop_index(op.f('ix_routes_8a+'), table_name='routes')
    op.drop_index(op.f('ix_routes_8a'), table_name='routes')
    op.drop_index(op.f('ix_routes_7c+'), table_name='routes')
    op.drop_index(op.f('ix_routes_7c'), table_name='routes')
    op.drop_index(op.f('ix_routes_7b+'), table_name='routes')
    op.drop_index(op.f('ix_routes_7b'), table_name='routes')
    op.drop_index(op.f('ix_routes_7a+'), table_name='routes')
    op.drop_index(op.f('ix_routes_7a'), table_name='routes')
    op.drop_index(op.f('ix_routes_6c+'), table_name='routes')
    op.drop_index(op.f('ix_routes_6c'), table_name='routes')
    op.drop_index(op.f('ix_routes_6b+'), table_name='routes')
    op.drop_index(op.f('ix_routes_6b'), table_name='routes')
    op.drop_index(op.f('ix_routes_6a+'), table_name='routes')
    op.drop_index(op.f('ix_routes_6a'), table_name='routes')
    op.drop_index(op.f('ix_routes_5c'), table_name='routes')
    op.drop_index(op.f('ix_routes_5b'), table_name='routes')
    op.drop_index(op.f('ix_routes_5a'), table_name='routes')
    op.drop_index(op.f('ix_routes_4+'), table_name='routes')
    op.drop_index(op.f('ix_routes_4'), table_name='routes')
    op.drop_index(op.f('ix_routes_3'), table_name='routes')
    op.drop_index(op.f('ix_routes_2'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_months_september'), table_name='months')
    op.drop_index(op.f('ix_months_october'), table_name='months')
    op.drop_index(op.f('ix_months_november'), table_name='months')
    op.drop_index(op.f('ix_months_may'), table_name='months')
    op.drop_index(op.f('ix_months_mars'), table_name='months')
    op.drop_index(op.f('ix_months_june'), table_name='months')
    op.drop_index(op.f('ix_months_july'), table_name='months')
    op.drop_index(op.f('ix_months_january'), table_name='months')
    op.drop_index(op.f('ix_months_february'), table_name='months')
    op.drop_index(op.f('ix_months_destination_id'), table_name='months')
    op.drop_index(op.f('ix_months_december'), table_name='months')
    op.drop_index(op.f('ix_months_august'), table_name='months')
    op.drop_index(op.f('ix_months_april'), table_name='months')
    op.drop_table('months')
    op.drop_index(op.f('ix_cost_weekly_avg'), table_name='cost')
    op.drop_index(op.f('ix_cost_tent'), table_name='cost')
    op.drop_index(op.f('ix_cost_hotel'), table_name='cost')
    op.drop_index(op.f('ix_cost_hostel'), table_name='cost')
    op.drop_index(op.f('ix_cost_destination_id'), table_name='cost')
    op.drop_index(op.f('ix_cost_apartment'), table_name='cost')
    op.drop_table('cost')
    op.drop_index(op.f('ix_car_rent_scooter_locally'), table_name='car')
    op.drop_index(op.f('ix_car_rent_car_locally'), table_name='car')
    op.drop_index(op.f('ix_car_not_needed'), table_name='car')
    op.drop_index(op.f('ix_car_must_have'), table_name='car')
    op.drop_index(op.f('ix_car_good_to_have'), table_name='car')
    op.drop_index(op.f('ix_car_destination_id'), table_name='car')
    op.drop_table('car')
    op.drop_index(op.f('ix_approach_moderate'), table_name='approach')
    op.drop_index(op.f('ix_approach_hardcore'), table_name='approach')
    op.drop_index(op.f('ix_approach_easy'), table_name='approach')
    op.drop_index(op.f('ix_approach_destination_id'), table_name='approach')
    op.drop_table('approach')
    op.drop_index(op.f('ix_accomodation_van'), table_name='accomodation')
    op.drop_index(op.f('ix_accomodation_tent'), table_name='accomodation')
    op.drop_index(op.f('ix_accomodation_house'), table_name='accomodation')
    op.drop_index(op.f('ix_accomodation_hotel'), table_name='accomodation')
    op.drop_index(op.f('ix_accomodation_hostel'), table_name='accomodation')
    op.drop_index(op.f('ix_accomodation_destination_id'), table_name='accomodation')
    op.drop_index(op.f('ix_accomodation_camping'), table_name='accomodation')
    op.drop_index(op.f('ix_accomodation_apartment'), table_name='accomodation')
    op.drop_table('accomodation')
    op.drop_index(op.f('ix_destination_title'), table_name='destination')
    op.drop_index(op.f('ix_destination_country'), table_name='destination')
    op.drop_table('destination')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
