"""empty message

Revision ID: cb11dafe5ec9
Revises: 0c0eb5a167d3
Create Date: 2019-05-14 11:27:35.518392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb11dafe5ec9'
down_revision = '0c0eb5a167d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camping_per_day', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cost_camping_per_day'), ['camping_per_day'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_camping_per_day'))
        batch_op.drop_column('camping_per_day')

    # ### end Alembic commands ###
