"""Adding total_sport,total_trad,total_boulders

Revision ID: d51645fa9e9c
Revises: 81a2ee3df2e0
Create Date: 2019-01-24 10:54:28.218947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51645fa9e9c'
down_revision = '81a2ee3df2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_boulders', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_sport', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_trad', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_routes_total_boulders'), ['total_boulders'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_total_sport'), ['total_sport'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_total_trad'), ['total_trad'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_total_trad'))
        batch_op.drop_index(batch_op.f('ix_routes_total_sport'))
        batch_op.drop_index(batch_op.f('ix_routes_total_boulders'))
        batch_op.drop_column('total_trad')
        batch_op.drop_column('total_sport')
        batch_op.drop_column('total_boulders')

    # ### end Alembic commands ###
