"""adding additional user properties

Revision ID: e21aae64252b
Revises: d51645fa9e9c
Create Date: 2019-03-05 14:46:10.140453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21aae64252b'
down_revision = 'd51645fa9e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=280), nullable=True))
        batch_op.add_column(sa.Column('displayname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_displayname'), ['displayname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_location'), ['location'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_location'))
        batch_op.drop_index(batch_op.f('ix_user_displayname'))
        batch_op.drop_column('location')
        batch_op.drop_column('displayname')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
