"""Added weather longitude and latitude to destination table

Revision ID: e4a4d58bd6c6
Revises: a8f8ced74f75
Create Date: 2019-05-11 13:32:46.697602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a4d58bd6c6'
down_revision = 'a8f8ced74f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather_lng', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weather_ltd', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.drop_column('weather_ltd')
        batch_op.drop_column('weather_lng')

    # ### end Alembic commands ###
